package se.velocius.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Stock")
public class Stock {

	private String sid;
	private String name;
	private String yahooTicker;
	private String label;

	@DynamoDBHashKey(attributeName = "Sid")
	@DynamoDBAutoGeneratedKey
	public String getSid() {
		return sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	@DynamoDBRangeKey(attributeName = "Name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = "YahooTicker")
	public String getYahooTicker() {
		return yahooTicker;
	}

	public void setYahooTicker(String yahooTicker) {
		this.yahooTicker = yahooTicker;
	}

	@DynamoDBAttribute(attributeName = "Label")
	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Override
	public String toString() {
		return "Stock [sid=" + sid + ", name=" + name + ", yahooTicker="
				+ yahooTicker + ", label=" + label + "]";
	}

}
