package se.velocius.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Stock")
public class Stock {

	private String sid;
	private String name;
	private String yahooTicker;
	private String label;
	private double stopPrice;
	private double trailingStopPercent;
	private int noShares;
	private double costBasis;
	private double sekValue;
	private double gain;

	@DynamoDBHashKey(attributeName = "Sid")
	@DynamoDBAutoGeneratedKey
	public String getSid() {
		return sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	@DynamoDBRangeKey(attributeName = "Name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = "YahooTicker")
	public String getYahooTicker() {
		return yahooTicker;
	}

	public void setYahooTicker(String yahooTicker) {
		this.yahooTicker = yahooTicker;
	}

	@DynamoDBAttribute(attributeName = "Label")
	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@DynamoDBAttribute(attributeName = "StopPrice")
	public double getStopPrice() {
		return stopPrice;
	}

	public void setStopPrice(double stopPrice) {
		this.stopPrice = stopPrice;
	}

	@DynamoDBAttribute(attributeName = "TrailingStopPercent")
	public double getTrailingStopPercent() {
		return trailingStopPercent;
	}

	public void setTrailingStopPercent(double trailingStopPercent) {
		this.trailingStopPercent = trailingStopPercent;
	}

	public int getNoShares() {
		return noShares;
	}

	public void setNoShares(int noShares) {
		this.noShares = noShares;
	}

	public double getCostBasis() {
		return costBasis;
	}

	public void setCostBasis(double costBasis) {
		this.costBasis = costBasis;
	}

	public double getSekValue() {
		return sekValue;
	}

	public void setSekValue(double sekValue) {
		this.sekValue = sekValue;
	}

	public double getGain() {
		return gain;
	}

	public void setGain(double gain) {
		this.gain = gain;
	}

	@Override
	public String toString() {
		return "Stock [sid=" + sid + ", name=" + name + ", yahooTicker="
				+ yahooTicker + ", label=" + label + "]";
	}

}
